"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useBrainStageStore } from "@/store/useBrainStageStore";

/**
 * Encoder Lab — video player that drives the persistent brain
 * visualization from a per-keyframe activation timeline.
 *
 * As the video plays, this component:
 *   1. Watches the <video> element's currentTime via `timeupdate`.
 *   2. Finds the two surrounding keyframes in the activation
 *      timeline.
 *   3. Linearly interpolates per-parcel activations between them.
 *   4. Pushes the interpolated map into `useBrainStageStore.
 *      setParcelActivations`.
 *
 * Preview path: the activation timelines are Neurosynth composites
 * generated by `build_video_activations_preview.py`. Once the Colab
 * TRIBE notebook produces real per-frame predictions, those JSONs
 * land at the same path (`/activations/videos/<id>.json`) and the
 * driver renders them without code change.
 */

export type VideoKeyframe = {
  t: number;
  composition?: Array<[string, number]>;
  parcel_activations: Record<string, number>;
};

export type VideoActivationFile = {
  id: string;
  duration: number;
  source: string;
  license: string;
  citation: string;
  parcellation: string;
  methodology: string;
  video: {
    source_url: string;
    license: string;
    attribution: string;
    notes?: string;
  };
  frames: VideoKeyframe[];
};

function interpolateFrames(
  frames: VideoKeyframe[],
  t: number,
): Record<string, number> {
  if (frames.length === 0) return {};
  if (t <= frames[0].t) return frames[0].parcel_activations;
  if (t >= frames[frames.length - 1].t) {
    return frames[frames.length - 1].parcel_activations;
  }
  let lo = 0;
  for (let i = 1; i < frames.length; i++) {
    if (frames[i].t >= t) {
      lo = i - 1;
      break;
    }
  }
  const a = frames[lo];
  const b = frames[lo + 1];
  const k = (t - a.t) / (b.t - a.t);
  const out: Record<string, number> = {};
  const keys = new Set<string>([
    ...Object.keys(a.parcel_activations),
    ...Object.keys(b.parcel_activations),
  ]);
  for (const key of keys) {
    const av = a.parcel_activations[key] ?? 0;
    const bv = b.parcel_activations[key] ?? 0;
    out[key] = av + (bv - av) * k;
  }
  return out;
}

type Props = {
  videoId: string;
  videoSrc: string;
  posterSrc: string;
  file: VideoActivationFile;
};

export default function VideoTimelineDriver({
  videoId,
  videoSrc,
  posterSrc,
  file,
}: Props) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [time, setTime] = useState(0);
  const [playing, setPlaying] = useState(false);

  const setParcelActivations = useBrainStageStore(
    (s) => s.setParcelActivations,
  );
  const resetIdle = useBrainStageStore((s) => s.resetIdle);

  // Sort frames once.
  const frames = useMemo(
    () => [...file.frames].sort((a, b) => a.t - b.t),
    [file.frames],
  );

  // Push interpolated activations on time change.
  useEffect(() => {
    const map = interpolateFrames(frames, time);
    setParcelActivations(map);
  }, [time, frames, setParcelActivations]);

  // Subscribe to <video> timeupdate.
  useEffect(() => {
    const el = videoRef.current;
    if (!el) return;
    const onTime = () => setTime(el.currentTime);
    const onPlay = () => setPlaying(true);
    const onPause = () => setPlaying(false);
    el.addEventListener("timeupdate", onTime);
    el.addEventListener("play", onPlay);
    el.addEventListener("pause", onPause);
    return () => {
      el.removeEventListener("timeupdate", onTime);
      el.removeEventListener("play", onPlay);
      el.removeEventListener("pause", onPause);
    };
  }, []);

  // Cleanup: reset brain when this video unmounts (gallery swap).
  useEffect(() => {
    return () => resetIdle();
  }, [resetIdle]);

  return (
    <div className="w-full">
      <video
        ref={videoRef}
        src={videoSrc}
        poster={posterSrc}
        controls
        preload="metadata"
        playsInline
        // Looping is editorially appropriate for short timelapses;
        // longer clips don't auto-loop. Threshold: 12 seconds.
        loop={file.duration <= 12}
        className="bg-navy-deep/40 w-full rounded-sm shadow-lg"
        data-video-id={videoId}
        aria-label={file.video.attribution}
      />
      {/* Small scrub-position indicator + play-state — most user
          interaction goes through the native controls; this is a
          quiet status line for the brain-driving timeline. */}
      <div className="text-bone-cream/40 mt-2 flex items-center justify-between font-mono text-[0.65rem] tracking-[0.16em] uppercase">
        <span>{playing ? "Playing" : "Paused"}</span>
        <span>
          {time.toFixed(1)}s / {file.duration.toFixed(1)}s
        </span>
      </div>
    </div>
  );
}
